version: '3.8'

services:
  betaflight-configurator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betaflight-configurator
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - betaflight-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=betaflight-configurator"
      - "com.docker.compose.service=betaflight-configurator"

networks:
  betaflight-network:
    driver: bridge
